// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footerNav: string;
export const navItem: string;
export const footerCopyLinks: string;
